# Generated by Django 5.2.8 on 2025-11-11 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('1', 'Artico'), ('2', 'Costeiro'), ('3', 'Deserto'), ('4', 'Floresta'), ('5', 'Campo'), ('6', 'Morro'), ('7', 'Montanha'), ('8', 'Pantano'), ('9', 'Subterraneo'), ('10', 'Urbano'), ('11', 'Maritmo')], default='2', max_length=2)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Assentamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('V', 'Vilarejo, até 500 habitantes, preço máximo de itens a venda 50 GP'), ('C', 'Cidade, de 5001 a 5000 habitantes, preço máximo de itens a venda 2.000 GP'), ('M', 'Metrópole, mais de 5000 habitantes, preço máximo de itens a venda 200.000 GP')], default='V', max_length=2)),
                ('caracteristica', models.CharField(choices=[('1', 'Muralhas Fortificadas'), ('2', 'Parques, Jardins e Vegetação Abundante'), ('3', 'Lama, lixo e imundice'), ('4', 'Cemitério extenso'), ('5', 'Nevoeiro Persistente'), ('6', 'Sons e Fumaça de Forjas'), ('7', 'Canais Substituem as ruas muitas pontes os cruzam'), ('8', 'Fronteira com penhasco'), ('9', 'Ruas e Construções bem mantidas e limpas'), ('10', 'Ruínas Antigas em meio ao assentamento'), ('11', 'Mercado/Bazar com aromas e itens exóticos'), ('12', 'Estrutura Impressionante (Castelo, Templo, Circulo de pedras ou Zigurate/Piramide)')], default='2', max_length=2)),
                ('fama', models.CharField(choices=[('1', 'Comida Deliciosa'), ('2', 'População Rude'), ('3', 'População Amigável'), ('4', 'Artistas e Escritores'), ('5', 'Grande Heroi/Salvador local'), ('6', 'Flores'), ('7', 'Festival Anual'), ('8', 'Assombrações'), ('9', 'Conjuradores de Magia'), ('10', 'Decadencia'), ('11', 'Piedade'), ('12', 'Apostas'), ('13', 'Aversão a Religião'), ('14', 'Educação'), ('15', 'Vinhos/Vinhedos'), ('16', 'Moda/Alta Costura'), ('17', 'Intriga Política'), ('18', 'Guildas Poderosas'), ('19', 'Patriotismo'), ('20', 'Ruínas Antigas')], default='1', max_length=2)),
                ('calamidades', models.CharField(choices=[('1', 'Infestção de Monstros'), ('2', 'Suspeita de assassinato do lider local'), ('3', 'Guerra iminente entre guildas/gangues locais'), ('4', 'Pragas/Fome provocam rebelião'), ('5', 'Monstros atacam qualquer um que se aproxima ou tenta deixar o assentamento'), ('6', 'Disputas comerciais criam crise economica'), ('7', 'Desastre natural ameaça o assentamento'), ('8', 'Profecia terrivel assusta moradores'), ('9', 'População em alistamento para guerra'), ('10', 'Violencia devido a intrigas políticas/religiosas'), ('11', 'Assentamento sob cerco'), ('12', 'Escandalo ameaça famílias nobres')], default='1', max_length=2)),
                ('lider', models.CharField(choices=[('1', 'Lider/Conselho Justos e Respeitados'), ('2', 'Tirano Temido'), ('3', 'Covarde Manipulado por outros'), ('4', 'Lider conhecidamente Ilegítmo e rejeitado'), ('5', 'Monstro poderoso'), ('6', 'Conspiradores anonimos misteriosos'), ('7', 'Liderança em disputa aberta e violenta'), ('8', 'Conselho disputado incapaz de tomar decisões'), ('9', 'Lider conhecidamente Imbecil/Idiota'), ('10', 'Lider moribundo com sucessão disputada'), ('11', 'Lider/Conselho mão-de-ferro respeitado'), ('12', 'Lider/Conselho religioso')], default='1', max_length=2)),
                ('bioma', models.ManyToManyField(to='mapa.bioma')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('Raça', models.CharField(max_length=60, unique=True)),
                ('Aparencia', models.CharField(choices=[('1', 'Ostenta Joias Diferenciadas'), ('2', 'Roupas Diferenciadas (Chamativas, Estrangeiras, Formais ou Trapos)'), ('3', 'Dispositivo Auxiliar de Marcha elegante (Bengala, cadeira de rodas/flutuante, tala/exoesqueleto)'), ('4', 'Cicatriz Marcante'), ('5', 'Olhos de cor incomum (ou de 2 cores diferentes)'), ('6', 'Tatuagens/Piercings'), ('7', 'Marca de Nascença'), ('8', 'Cabelos de cor incomum'), ('9', 'Careca OU Barba/Cabelo trançado'), ('10', 'Nariz distinto (grande/pequeno ou quebrado ou bulboso)'), ('11', 'Postura distinta (Encurvado ou Rígido)'), ('12', 'Extremamente belo/feio')], default='1', max_length=2)),
                ('Segredo', models.CharField(choices=[('1', 'Disfarçado, ocultando identidade ou aspecto especifico da aparencia'), ('2', 'Planejando/Executando/Escondendo um crime'), ('3', 'Esta pessoa ou a família dela foi ameaçada de morte caso deixe de fazer algo'), ('4', 'Magicamente influenciada a se comportar de determinada forma'), ('5', 'Terrivelmente doente ou acometido por dor crônica'), ('6', 'Se sente responsável pela morte/infortúnio de alguém'), ('7', 'Prestes a falir catastroficamente'), ('8', 'Desesperadamente carente ou nutrindo paixão não correspondida'), ('9', 'Nutrindo uma ambição poderosa'), ('10', 'Profundamente insatisfeito/deprimido')], default='1', max_length=2)),
                ('Origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.assentamento')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('1', 'Penhora'), ('2', 'Apotecário'), ('3', 'Mercearia'), ('4', 'Iguarias Finas/Exóticas'), ('5', 'Olaria'), ('6', 'Funerária'), ('7', 'Livraria'), ('8', 'Banco'), ('9', 'Armoraria'), ('10', 'Velas e Incensos'), ('11', 'Forja/Oficina'), ('12', 'Carpintaria'), ('13', 'Ateliê'), ('14', 'Joalheria'), ('15', 'Padaria'), ('16', 'Cartografo'), ('17', 'Alfaiate'), ('18', 'Cordoaria'), ('19', 'Construtora'), ('20', 'Biblioteca')], default='13', max_length=2)),
                ('lojista', models.ManyToManyField(to='mapa.personagem')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
