# Generated by Django 5.2.8 on 2025-11-11 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='Aparencia',
            new_name='aparencia',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='Origem',
            new_name='origem',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='Raça',
            new_name='raca',
        ),
        migrations.RenameField(
            model_name='personagem',
            old_name='Segredo',
            new_name='segredo',
        ),
    ]
