# Generated by Django 5.2.8 on 2025-11-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_rename_aparencia_personagem_aparencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assentamento',
            old_name='calamidades',
            new_name='calamidade',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='lojista',
        ),
        migrations.AddField(
            model_name='loja',
            name='lojista',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loja', to='mapa.personagem'),
        ),
    ]
