# Generated by Django 5.2.8 on 2025-11-12 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_rename_calamidades_assentamento_calamidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaMundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('imagem', models.ImageField(upload_to='mapas/')),
                ('largura', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('altura', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='assentamento',
            name='pos_x',
            field=models.FloatField(blank=True, help_text='Coordenada X (px) na imagem do mapa', null=True),
        ),
        migrations.AddField(
            model_name='assentamento',
            name='pos_y',
            field=models.FloatField(blank=True, help_text='Coordenada Y (px) na imagem do mapa', null=True),
        ),
        migrations.AddField(
            model_name='assentamento',
            name='mapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assentamentos', to='mapa.mapamundo'),
        ),
    ]
