# Generated by Django 5.2.8 on 2025-11-12 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_mapamundo_assentamento_pos_x_assentamento_pos_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioma',
            name='cor',
            field=models.CharField(blank=True, default='#88cc66', max_length=7),
        ),
        migrations.AddField(
            model_name='bioma',
            name='mapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biomas', to='mapa.mapamundo'),
        ),
        migrations.AddField(
            model_name='bioma',
            name='poligonos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='assentamento',
            name='bioma',
            field=models.ManyToManyField(blank=True, to='mapa.bioma'),
        ),
    ]
