# Generated by Django 5.2.8 on 2025-11-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_bioma_cor_bioma_mapa_bioma_poligonos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='catalogo',
            field=models.CharField(blank=True, help_text='Descrição resumida dos itens vendidos pela loja', max_length=1500, null=True),
        ),
    ]
