# Generated by Django 5.2.8 on 2025-11-15 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_loja_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='assentamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='mapa.assentamento'),
        ),
    ]
