# Generated by Django 5.2.8 on 2025-11-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0007_loja_assentamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='assentamento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do assentamento/cidade', null=True),
        ),
    ]
