# Generated by Django 5.2.8 on 2025-11-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0008_assentamento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='raca',
            field=models.CharField(max_length=60),
        ),
    ]
